version: '3.8' 

services:
  app:
    build: . # Path to the directory with your app's Dockerfile
    ports:
      - "8005:8000" # Expose FastAPI's port
    depends_on:
      - postgres_db
    environment:
      - DATABASE_URL=postgresql://postgres:1234@postgres_db:5432/complaint
    volumes:
      - complaint_data:/app/bot/Complaintbot/botpickle
      - hr_data:/app/bot/Hrbot/botpickle
      - complaint_file:/app/files

  postgres_db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=complaint

volumes:
  postgres_data:
  complaint_data:
  hr_data:
  complaint_file: